# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rfc_cliente', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('nombre_cliente', models.TextField(blank=True, null=True)),
                ('direccion_cliente', models.TextField(blank=True, null=True)),
                ('telefono_cliente', models.TextField(blank=True, null=True)),
                ('email_cliente', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Cliente',
                'managed': False,
            },
        ),
    ]
