# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('rfc_medico', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('nombre_medico', models.TextField(blank=True, null=True)),
                ('direccion_medico', models.TextField(blank=True, null=True)),
                ('telefono_medico', models.TextField(blank=True, null=True)),
                ('email_medico', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Medico',
                'managed': False,
            },
        ),
    ]
